# This file configures the secret scanning feature of GitHub.
# For more information, see https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning
paths-ignore:
  - "tests/**"
  - "docs/**"